# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: get keyvault to .env
        id: getsecret
        uses: Andrews-McMeel-Universal/get-envs@v1
        with:
          environmentKeyVault: kv-kkimura-20241007
          azurecredentials: ${{ secrets.AZURE_CREDENTIALS }}

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cat .env
